name: Build and deploy
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - uses: hecrj/setup-rust-action@v1
              with:
                  rust-version: stable

            - uses: actions/checkout@master

            - run: yarn
            - run: yarn bootstrap:production
            - run: yarn build:production

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
